set +h
umask 022
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/usr/bin
if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
PATH=$XLFS/tools/bin:$PATH
CONFIG_SITE=$XLFS/usr/share/config.site
export XLFS HOME LC_ALL LFS_TGT PATH CONFIG_SITE
export MAKEFLAGS=-j8
